server:
  port: "8080"
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://${JDBC_DATABASE_HOST:localhost}:${JDBC_DATABASE_PORT:5432}/${JDBC_DATABASE_NAME:mydatabase}"
    username: "${JDBC_DATABASE_USERNAME:admin}"
    password: "${JDBC_DATABASE_PASSWORD:admin}"
  jpa:
    hibernate:
      ddl-auto: "update"