server:
  port: "8080"
spring:
  datasource:
    url: "jdbc:h2:mem:dev_db"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  h2:
    console:
      enabled: "true"
  jpa:
    open-in-view: "false"
    show-sql: "true"
    properties:
      hibernate:
        format_sql: "true"